export enum ErrorType {
    USER_TYPE_IS_NOT_A_VALID_VALUE = "ERROR.USER_TYPE_IS_NOT_A_VALID_VALUE",
    THIS_USER_NAME_IS_TAKEN = "ERROR.THIS_USER_NAME_IS_TAKEN",
    USER_NOT_FOUND = "ERROR.USER_NOT_FOUND",
    WRONG_PASSWORD = "ERROR.WRONG_PASSWORD",
    NOT_VALID_PASSWORD_TYPE = 'ERROR.NOT_VALID_PASSWORD_TYPE',
    NOT_VALID_USER_NAME = 'ERROR.NOT_VALID_USER_NAME',
    SHORT_PASSWORD = "ERROR.SHORT_PASSWORD",
    UNAUTHORIZED = "ERROR.UNAUTHORIZED",
    UNEXPECTED = "ERRORS.UNEXPECTED"
}