export enum MovementType {
    USER_CREATED = 'USER_CREATED',

    FAIL_LOGIN = 'FAIL_LOGIN',
    SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN',
    
    SUCCESSFUL_UPDATE = 'SUCCESSFUL_UPDATE',
    FAIL_UPDATE = 'FAIL_UPDATE',
    
    SUCCESS_PASSWORD_UPDATE = 'SUCCESS_PASSWORD_UPDATE',
    FAIL_PASSWORD_UPDATE = 'FAIL_PASSWORD_UPDATE',
    
    SUCCESS_USERNAME_UPDATE = 'SUCCESS_USERNAME_UPDATE',
    FAIL_USERNAME_UPDATE = 'FAIL_USERNAME_UPDATE',
    
}